version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
    - master
before_build:
  ps: nuget restore GiphyPropertyEditor.sln
build:
  project: GiphyPropertyEditor/GiphyPropertyEditor.csproj
  publish_nuget: true
  verbosity: detailed
